// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

public type Lecturer_courses record {
    string courseName?;
    string courseCode?;
    string nqfLevel?;
};

public type Lecturer record {
    string staffNumber?;
    string officeNumber?;
    string staffName?;
    string title?;
    Lecturer_courses[] courses?;
};

public type Inline_response_201 record {
    # the username of the lecturer newly created
    string userid?;
};
